### ISSUE TITLE
4.4.20 is missing 4.4.19 commits

### ISSUE THREAD

**Issue by wizu** [QIDITECH/QIDI_Q1_Pro#43]
When comparing 4.4.20 branch with main it shows, that 4.4.20 is missing two commits - one with code changes:
https://github.com/QIDITECH/QIDI_Q1_Pro/compare/V4.4.20...main
Are those changes in 4.4.20 firmware version?

These look important:
https://github.com/QIDITECH/QIDI_Q1_Pro/commit/16e6ad674ba588ac49c5272032a259555dba1aa9

**Comment by CChen616** [comment]
That's because the current branch 4.4.20 hasn't been merged into the main branch yet. These two commits were generated when version 4.4.19 was previously merged into the main branch. The current branch 4.4.20 was created based on the last commit of 4.4.19 and contains the latest content. If you want to compare differences, it's recommended to compare with branch 4.4.19.
